{{- $fullName := include "pycsw.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-configmap
data:
  location.conf: {{ tpl (.Files.Get "config/location.conf") . | quote }}
