{{- $fullName := include "pycsw.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-configmap
data:
  default.conf: {{ tpl (.Files.Get "config/default.conf") . | quote }}
