{{- define "pycsw-chart.uwsgi-exporter-container" }}
        - name: uwsgi-exporter
          image: {{ .cloudProviderDockerRegistryUrl }}{{ .Values.uwsgiExporter.image.repository }}:{{ .Values.uwsgiExporter.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }} 
          args:
            - "--stats.uri=http://localhost:{{ .Values.env.uwsgi.statsServer.stats }}"
            - "--log.level={{ .Values.uwsgiExporter.env.logLevel }}"
          {{- if .resources.enabled }}
          resources:
            {{- toYaml .resources.value | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: "/-/healthy"
              port: "uwsgimetrics"
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: "/metrics"
              port: "uwsgimetrics"
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - name: "uwsgimetrics"
              containerPort: {{ .Values.uwsgiExporter.port }}
{{- end }}
