{{- if .Values.authentication.opa.enabled }}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "pycsw.name" . -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-opa
data:
  policy.rego: |-
{{ tpl (.Files.Get "config/policy.rego") . | b64enc | indent 4 }}
{{- end }}
