{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
data:
  default.conf: {{ tpl (.Files.Get "config/default.conf") . | quote }}
  nginx.conf: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
{{- end }}
