{{- $chartName := include "pycsw.name" . -}}
{{- $tracingUrl := include "pycsw.tracingUrl" . -}}
{{- $metricsUrl := include "pycsw.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  pycsw.cfg: {{ tpl (.Files.Get "config/pycsw.cfg") . | quote }}
  mappings.py: {{ .Files.Get "config/mappings.py" | quote }}
  uwsgi.ini: {{ tpl (.Files.Get "config/pycswWsgi.ini") . | quote }}
  CORS_ENABLED: {{ .Values.env.cors.enabled | quote }}
  CORS_ALLOWED_HEADERS: {{ template "pycsw.cors.allowedHeaders" . }}
  CORS_ALLOWED_ORIGIN: {{ .Values.env.cors.allowedOrigin | quote }}
  LOG_FORMAT: {{ .Values.env.logFormat | quote }}
  DB_HOST: {{ quote .Values.rasterCommon.db.host }}
  DB_PORT:  {{ quote .Values.rasterCommon.db.port }}
  DB_NAME: {{ quote .Values.rasterCommon.db.name }}
  POSTGRES_ENABLE_SSL_AUTH: {{ quote .Values.rasterCommon.db.sslEnabled }}
  DB_SCHEMA: {{ quote .Values.env.db.schema }}
{{- end }}
