kind: Secret
apiVersion: v1
metadata:
  name: map-colonies-jwks
data:
  mapColonies.jwks: >-
    eyJrZXlzIjpbeyJrdHkiOiJSU0EiLCJuIjoicTVuSnpQcjB0RW43YzI0Z2JFbThtcENXSV9BRjhDN2M1d1ZTdzZ2MXozSi1NQjFyaU1YWTVGUGZyVTNwdUQ4MmREN3NyVVpMZ3pYYjdPZ3RsejBURFhBQndXenljcWdMa0g2eW0xbkVlYy1RVW5KWW50YkxoN0g3ZFJvRjVaQzFmejYtSVhnVTJnYi0wTzVaN3UyMFJOUFRSR01PbnFWT2d1TUZMMnN0UzBBQXlTY3cydHV5TzdfOHROZjl4ZTZ4VUtGcUpPaVNYa05nd0hIS0p5ZWJBTWpUZzJDaUJJMzZualNTVElGeEc5eUVzLVFWZFBnTlpKN0pTaU1wTVppTElSUnpnV1NvdzBOMktkMHZwMFI4ZG1CYkhvdFgwLW9xdm5rMUNPeTdlV3R3U2VjQjRBeU9RRGp3M3kwU182T3pDVU50TUxCcW5nekJmcW8wMDU4VmNRIiwiZSI6IkFRQUIiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1hcENvbG9uaWVzUUEifV19

