if ($request_method = 'POST') {
    add_header 'Access-Control-Allow-Origin' {{ .Values.nginx.allowedOrigins | default "*" | squote }} always;
    add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' {{ .Values.nginx.allowedHeaders | default "*" | squote }} always;
    add_header 'Access-Control-Max-Age' {{ .Values.nginx.maxAge | default "3600" | squote }};
}

proxy_hide_header Set-Cookie;  # ensures the header will not be passed back to the client
proxy_ignore_headers Set-Cookie;  # ensures that the header will not automatically disable caching within nginx
proxy_set_header  Cookie ""; # ensures that a client cannot pass any prior cookies to the webapp and spoil your cacheCollapse comment
