apiVersion: v2
name: pycsw
description: A Helm chart for pycsw service
type: application
version: 6.1.0
appVersion: 6.1.0
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
  - name: mc-labels-and-annotations
    version: 0.5.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
