apiVersion: v2
name: pycsw
description: A Helm chart for pycsw service
type: application
version: 6.2.2
appVersion: 6.2.2
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
