apiVersion: v2
name: pycsw
description: A Helm chart for pycsw service
type: application
version: 4.5.3
appVersion: 4.5.3
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
