{{- $resourceName := print .Release.Name "-ingress" }}
{{- $pycswService := print .Release.Name "-pycsw" }}
{{- $pgadmin4Service := print .Release.Name "-pgadmin4" }}
{{- with .Values -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $resourceName }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/pycsw"
        backend:
          service:
            name: {{ $pycswService }}
            port:
              number: 8000
  {{- if .pgadmin4.enabled }}
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $pgadmin4Service }}
            port:
              number: 80
  {{- end -}}
{{- end -}}
