{{- $resourceName := print .Release.Name "-ingress" }}
{{- $pycswService := print .Release.Name "-pycsw" }}
{{- $releaseName := print .Release.Name "-pycsw" }}
{{- $pgadmin4Service := print .Release.Name "-pgadmin4" }}
{{- with .Values -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $resourceName }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/{{ $releaseName }}/pycsw"
        backend:
          service:
            name: {{ $pycswService }}
            port:
              number: 8000
{{- end -}}
