{{- $resourceName := print .Release.Name "-pgadmin4-configmap" }}
{{- $postgresName := print .Release.Name "-postgres" }}
{{- with .Values -}}
{{- if and .pgadmin4.enabled .postgres.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $resourceName }}
data:
  servers.json: |+
    {
      "Servers": {
        "1": {
          "Name": "{{ $postgresName }}",
          "Group": "Servers",
          "Host": "{{ $postgresName }}",
          "Port":  5432 ,
          "MaintenanceDB": "{{ .postgres.db_name }}",
          "Username": "{{ .postgres.authentication.username }}",
          "SSLMode": "prefer",
          "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
          "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
          "SSLCompression": 0,
          "Timeout": 10,
          "UseSSHTunnel": 0,
          "TunnelPort": "22",
          "TunnelAuthentication": 0
        }
      }
    }
{{- end -}}
{{- end -}}
