{{- $resourceName := print .Release.Name "-pgadmin4" }}
{{- with .Values -}}
{{- if .pgadmin4.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ $resourceName }}
  name: {{ $resourceName }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: {{ $resourceName }}
status:
  loadBalancer: {}
{{- end -}}
{{- end -}}
