{{- $resourceName := print .Release.Name "-postgres" -}}
{{- with .Values.postgres }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ $resourceName }}
  name: {{ $resourceName }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: {{ $resourceName }}
status:
  loadBalancer: {}
{{- end -}}
