{{- $resourceName := print .Release.Name "-postgres" -}}
{{- $resourcePV := print .Release.Name "-postgres-pv" -}}
{{ with .Values.postgres }}
{{ if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ $resourceName }}
  name: {{ $resourceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ $resourceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $resourceName }}
    spec:
      containers:
      - env:
        - name: PGDATA
          value: {{ .pg_data_path }}
        - name: POSTGRES_DB
          value: {{ .db_name }}
        - name: POSTGRES_PASSWORD
          value: {{ .authentication.password }}
        - name: POSTGRES_USER
          value: {{ .authentication.username }}
        image: postgis/postgis:12-3.0-alpine
        name: {{ $resourceName }}
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: {{ .pg_data_path }}
          name: {{ $resourcePV }}
      restartPolicy: Always
      volumes:
      - name: {{ $resourcePV }}
        persistentVolumeClaim:
          claimName: {{ $resourcePV }}
status: {}
{{ end }}
{{ end }}