{{- $resourceName := print .Release.Name "-pycsw-configmap" }}
{{- with .Values.pycsw -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $resourceName }}
data:
  pycsw.cfg: |+ 
{{ .pycsw_cfg | indent 4 }}
  {{- if .mappings_py }}
  mappings.py: |+ 
{{ .mappings_py | indent 4}}
  {{- end -}}
{{- end -}}