{{- $resourceName := print .Release.Name "-pycsw" }}
{{- $resourceConfigmap := print .Release.Name "-pycsw-configmap" }}
{{- $postgresName := print .Release.Name "-postgres" }}
{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ $resourceName }}
  name: {{ $resourceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ $resourceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $resourceName }}
    spec:
      containers:
      - env:
        - name: PYCSW_SERVER_URL
          value: http://localhost:8000
        {{- if .postgres.enabled }}
        - name: PYCSW_REPOSITORY_DATABASE_URI
          value: postgresql://{{ .postgres.authentication.username }}:{{ .postgres.authentication.password }}@{{ .postgres.host }}/{{ .postgres.db_name }}
        {{- end }}
        {{- if .pycsw.mappings_py }}
        - name: PYCSW_MAPPINGS_FILEPATH
          value: /etc/pycsw/mappings.py
        {{- end }}
        image: {{ .pycsw.image }}
        imagePullPolicy: Always
        name: {{ $resourceName }}
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /etc/pycsw
          name: {{ $resourceConfigmap }}
      restartPolicy: Always
      volumes:
      - name: {{ $resourceConfigmap }}
        configMap:
          name: {{ $resourceConfigmap }}
status: {}
{{- end -}}
