{{- $resourceName := print .Release.Name "-ingress" }}
{{- $pycswService := print .Release.Name "-pycsw" }}
{{- $releaseName := print .Release.Name "-pycsw" }}
{{- $pgadmin4Service := print .Release.Name "-pgadmin4" }}
{{- with .Values -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-web-route
spec:
  path: "/pycsw"
  to:
    kind: Service
    name: {{ $pycswService }}
  {{- if .route.tls -}}
  tls:
    termination: edge
  {{- end -}}
{{- end -}}
