name: pull_request

on: [pull_request]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Project Git repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        id: build_docker_image
        uses: MapColonies/shared-workflows/actions/build-docker@build-docker-v1
        with:
          registry: ${{ secrets.ACR_URL }}


